services:
  nginx:
    container_name: prod-llmsizer-nginx
    ports: !override
      - "127.0.0.1:20800:80"

networks:
  default:
    name: prod-llmsizer
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.9.0/24
